// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ7OC30P5VT4Zhcelvy8lrORsJ5JVAmug',
    appId: '1:34715017554:web:74b79f0a00f062f49a5a8b',
    messagingSenderId: '34715017554',
    projectId: 'messagingapp-f440c',
    authDomain: 'messaging-f440c.firebaseapp.com',
    storageBucket: 'messagingapp-f440c.firebasestorage.app',
    measurementId: 'G-M883LZE942',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5RNPNKrjNIhkW1YongUar8IOCT3N1wjQ',
    appId: '1:34715017554:android:f939d6fce441ab499a5a8b',
    messagingSenderId: '34715017554',
    projectId: 'messagingapp-f440c',
    storageBucket: 'messagingapp-f440c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOrYnlZrrbhOhHD3MZlZRXYBH2ywAilSk',
    appId: '1:34715017554:ios:13ea2a52997a4ff79a5a8b',
    messagingSenderId: '34715017554',
    projectId: 'messagingapp-f440c',
    storageBucket: 'messagingapp-f440c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOrYnlZrrbhOhHD3MZlZRXYBH2ywAilSk',
    appId: '1:34715017554:ios:13ea2a52997a4ff79a5a8b',
    messagingSenderId: '34715017554',
    projectId: 'messagingapp-f440c',
    storageBucket: 'messagingapp-f440c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ7OC30P5VT4Zhcelvy8lrORsJ5JVAmug',
    appId: '1:34715017554:web:05a4197e8f1129ea9a5a8b',
    messagingSenderId: '34715017554',
    projectId: 'messagingapp-f440c',
    authDomain: 'messagingapp-f440c.firebaseapp.com',
    storageBucket: 'messagingapp-f440c.firebasestorage.app',
    measurementId: 'G-TH44F9NS7T',
  );
}
